- name: Reboot remote host and create timestamped file
  hosts: remote_target
  become: yes
  tasks:
    - name: Reboot the remote host
      ansible.builtin.shell: sleep 2 && /sbin/shutdown -r now "Reboot via Ansible"
      async: 60
      poll: 0
      ignore_errors: true

    - name: Wait for remote host to become reachable
      ansible.builtin.wait_for_connection:
        delay: 5      # Number of seconds to wait before starting to poll.
        connect_timeout: 300  # Maximum number of seconds to wait for.
      register: wait_result
      retries: 3      # 
      delay: 10       # only start checking after 10 seconds
      until: wait_result is success

    - name: Get current timestamp in DDMMYY_HHmmss format
      ansible.builtin.shell: date +%d%m%y_%H%M%S
      register: timestamp
      changed_when: false

    - name: Create file named with timestamp
      ansible.builtin.file:
        path: "/home/ec2-user/{{ timestamp.stdout }}"
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: '0644'
